### ISSUE TITLE
Chromium crashes

### ISSUE THREAD

**Issue by jakepog** [CitrusIce/ImportBookmarksToZotero#1]
**Describe the bug** 
Chromium crashes. Sometimes ~8-10 tabs open, sometimes none open, then Chromium crashes. 

**Expected behaviour**
Open browser and tabs, import web pages into Zotero. 

**Error messages**
[03-24 17:15:38] p56438 {/Users/****/Library/Python/3.7/lib/python/site-packages/pyppeteer/launcher.py:208} INFO - terminate chrome process...

**System Info**
MacOS 12.3 (21E230)
Zotero version 6.0.1 
Python version 3.7.3

**Comment by jakepog** [comment]
I changed 
`"headless": False`
to 
`"headless": True`
but that also crashed.

**Comment by CitrusIce** [comment]
It seems like a crash from browser internal, not the python script and I can't reproduce the crash in my environment. But I think switching to chrome from chromium may help.

**Comment by jakepog** [comment]
It is already Chromium. Where in the script is the browser type set? I think it can also do Firefox?

**Comment by CitrusIce** [comment]
I don't know if pyppeteer support firefox.
For switching to chrome, just add the executablePath option to launch browser like:
```
await launch({
                    "executablePath":'<path to your chrome>',
                    "headless": False,
                    "userDataDir": path,
                    "args": [
                        "--no-sandbox",
                        "--ignore-certificate-errors",
                        "--load-extension={}".format(self.ext_path),
                        "--disable-extensions-except={}".format(self.ext_path),
                        "--proxy-server={}".format(self.proxy),
                    ],
                }) 
```

**Comment by jakepog** [comment]
Thanks. I was able to open in Google Chrome, but it still crashes. I can change the number of tabs that open before it crashes by modifying `self.max_tabs = 20`
Here is the traceback log: 

```Traceback (most recent call last):
File "main.py", line 265, in <module>
    asyncio.get_event_loop().run_until_complete(main())
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
File "main.py", line 239, in main
    bookmarks = bookmarks_parser.parse(args.bookmarks)
  
File "/Users/***/Library/Python/3.7/lib/python/site-packages/bookmarks_parser/bookmarks_parser.py", line 78, in parse
    bookmarks = process_dir(dls[0], 0)
  
File "/Users/***/Library/Python/3.7/lib/python/site-packages/bookmarks_parser/bookmarks_parser.py", line 51, in process_dir
    item_data = get_node_data(child)
  
File "/Users/***/Library/Python/3.7/lib/python/site-packages/bookmarks_parser/bookmarks_parser.py", line 37, in get_node_data
    if data['type'] == 'folder' and not data.get('__dir_dl'):

KeyError: 'type'

[04-08 08:18:21] p26281 {/Users/***/Library/Python/3.7/lib/python/site-packages/pyppeteer/launcher.py:208} INFO - terminate chrome process...
```

This appears to suggest that the bookmark_parser cannot open the bookmark file properly? I exported a list of 100 bookmarks from Firefox. I tried to break them into just 10 bookmarks, but that just crashes too.

**Comment by CitrusIce** [comment]
Yes, it's a crash from bookmark parser. Could you please upload a bookmarks list sample so that I can figure out what's the problem and fix it.

**Comment by jakepog** [comment]
```
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<!-- This is an automatically generated file.
     It will be read and overwritten.
     DO NOT EDIT! -->
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<meta http-equiv="Content-Security-Policy"
      content="default-src 'self'; script-src 'none'; img-src data: *; object-src 'none'"></meta>
<TITLE>thetorah</TITLE>
<H1>thetorah</H1>
<DL>
<DT>
    <DL><p>
      <DT><A HREF="https://www.thetorah.com/article/jonahs-magical-mystery-tour-of-the-netherworld"></A>
      <DT><A HREF="https://www.thetorah.com/article/yhwh-the-original-arabic-meaning-of-the-name"></A>
      <DT><A HREF="https://www.thetorah.com/article/he-tethers-his-donkey-to-the-vine-judah-exported-soreqa-wine"></A>
      <DT><A HREF="https://www.thetorah.com/article/2-and-4-maccabees-evolving-responses-to-hellenism"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-12th-century-derasha-on-parashat-vayishlach-reconstructing-the-speakers-notes"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-cognitive-confession-vidui-for-yom-kippur"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-corpse-left-hanging-overnight-is-a-cursing-of-god"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-faith-that-includes-doubt-psalm-27"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-feminist-literalist-allegorical-reading-of-shir-hashirim"></A>
      <DT><A HREF="https://www.thetorah.com/article/a-king-who-reads-torah-what-was-kingship-like-in-the-ane"></A>
    </DL>
</DT>
</DL>
```

**Comment by CitrusIce** [comment]
I have pushed a commit and the sample you provide can be parsed correctly.  Have a test.

**Comment by jakepog** [comment]
The update fixed the problem. Thanks! 
I also noted that I had set the number of tabs to be 16, which was just too many for my internet connection to reliably load at once, so 8 tabs took much longer but worked well.
